namespace: catalogue

replicaCount: 2

image:
  repository: 942548380129.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue
  tag: "1.0.0"
  digest: ""
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

env:
  MONGO: "true"

secret:
  enabled: true
  name: catalogue-secret
  mongoUrlKey: MONGO_URL

externalSecret:
  enabled: true
  secretStoreName: aws-secretsmanager
  secretStoreKind: ClusterSecretStore
  awsSecretName: roboshop/dev/catalogue
  refreshInterval: 1h

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  enabled: false
  className: alb
  scheme: internet-facing
  targetType: ip
  host: catalogue-dev.optimusprime.uno
  path: /
  pathType: Prefix