replicaCount: 2

image:
  repository: 942548380129.dkr.ecr.us-east-1.amazonaws.com/catalogue
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

namespace: catalogue

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
